spring:
  datasource:
    url: jdbc:mysql://localhost:3307/novel_park
    username: common
    password: asdf1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloud:
  aws:
    credentials:
      access-key: access-key
      secret-key: secret-key
    s3:
      bucket: bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

s3:
  default:
    profile-url: https://novel-park-bucket.s3.ap-northeast-2.amazonaws.com/public/profiles/default_profile.png

oauth:
  naver:
    client-id: clientId
    client-secret: clientSecret
    oauth-api-url: https://nid.naver.com/oauth2.0
    oauth-resource-url: https://openapi.naver.com/v1/nid
    redirect-url: redirect-url
  kakao:
    client-id: clientId
    client-secret: clientSecret
    oauth-api-url: https://kauth.kakao.com/oauth
    oauth-resource-url: https://kapi.kakao.com/v2/user
    redirect-url: redirect-url
