spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novel_park
    username: common
    password: asdf1234

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
